# Generated by Django 3.2.5 on 2023-10-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='firstname',
            new_name='fn',
        ),
    ]
