# Generated by Django 3.2.5 on 2023-10-07 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_firstname_reg_fn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg',
            old_name='fn',
            new_name='firstname',
        ),
    ]
