# Generated by Django 3.2.5 on 2023-10-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_fn_reg_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='firstname',
            field=models.CharField(max_length=20, null='true'),
        ),
    ]
