# Generated by Django 4.2.5 on 2023-10-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_reg_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='address',
            field=models.CharField(max_length=80),
        ),
    ]
