# Generated by Django 3.2.5 on 2023-10-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_jobposting'),
    ]

    operations = [
        migrations.CreateModel(
            name='workerreg1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('quilification', models.CharField(max_length=50)),
                ('contactno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
