# Generated by Django 3.2.5 on 2023-10-22 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_workerreg1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerreg1',
            name='location',
        ),
    ]
