# Generated by Django 3.2.5 on 2023-10-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_workerreg1_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='dailyweges',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='email',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='username',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
