# Generated by Django 3.2.5 on 2023-10-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20231024_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='dailyweges',
            new_name='dailywages',
        ),
    ]
