# Generated by Django 3.2.5 on 2023-12-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20231203_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerreg1',
            name='imgg',
            field=models.ImageField(upload_to=''),
        ),
    ]
