# Generated by Django 3.2.5 on 2023-12-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_workerreg1_imgg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workerbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('workername', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('requirement', models.TextField()),
                ('w_status', models.CharField(choices=[('waiting', 'waiting'), ('Request Accepted', 'Request Accepted'), ('Request Denied', 'Request Denied')], max_length=30)),
            ],
        ),
    ]
