# Generated by Django 3.2.5 on 2023-12-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
