# Generated by Django 3.2.5 on 2023-12-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_jobposting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='imgg',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
